[package]
name = "rust_database_project"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "2.0.17"
pest = "2.7.14"
pest_derive = "2.7.14"